name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{github.repository_owner}}/storypoints:${{ github.run_number }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: GH Docker Push
        run: |
          docker push ghcr.io/${{github.repository_owner}}/storypoints:${{ github.run_number }}
          docker image tag ghcr.io/${{github.repository_owner}}/storypoints:${{ github.run_number }} ghcr.io/${{github.repository_owner}}/storypoints:latest
          docker push ghcr.io/${{github.repository_owner}}/storypoints:latest
